export const ActionTypes = {
  SET_CITY: 'SET_CITY',
  SET_CURRENT_OFFER: 'SET_CURRENT_OFFER',
  SET_SORT_TYPE: 'SET_SORT_TYPE',
  LOAD_OFFERS: 'LOAD_OFFERS',
  LOAD_NEARBY_OFFERS: 'LOAD_NEARBY_OFFERS',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_ERROR: 'SET_ERROR',
  LOAD_REVIEWS: 'LOAD_REVIEWS',
  SET_AUTHORIZATION_REQUIRED: 'SET_AUTHORIZATION_REQUIRED'
};
