export const ActionTypes = {
  SET_CITY: 'SET_CITY',
  SET_SORT_TYPE: 'SET_SORT_TYPE',
  SET_CURRENT_OFFER: 'SET_CURRENT_OFFER',
  SET_USER_DATA: 'SET_USER_DATA',
  SET_AUTHORIZATION_REQUIRED: 'SET_AUTHORIZATION_REQUIRED',
  SET_ERROR: 'SET_ERROR',
  SET_SENDING_STATUS: 'SET_SENDING_STATUS',

  LOAD_OFFERS: 'LOAD_OFFERS',
  LOAD_NEARBY_OFFERS: 'LOAD_NEARBY_OFFERS',
  LOAD_REVIEWS: 'LOAD_REVIEWS',
  LOAD_FAVORITES: 'LOAD_FAVORITES',

  UPDATE_FAVORITES: 'UPDATE_FAVORITES',

  POST_REVIEW: 'POST_REVIEW',

  LOCK_FORM: 'LOCK_FORM'
};
